/**
 * Seal Rescue Engine - CDN JavaScript SDK
 * Version: 1.0.0
 * 
 * This SDK captures frontend errors and automatically fetches/applies
 * logical monkey-patches generated by the Seal AI Rescue Engine.
 */

(function(window) {
    'use strict';
  
    // Private state
    let config = {
      apiKey: null,
      appName: 'Frontend Client',
      rescueEngine: false,
      apiEndpoint: 'https://sealengine.desicon.ai/api/v1',
      patchCache: []
    };
  
    const Seal = {
      
      /**
       * Initialize the Seal SDK
       * @param {Object} options Configuration options
       */
      init: function(options) {
        if (!options || !options.apiKey) {
          console.warn('[Seal] API Key is required to initialize the SDK.');
          return;
        }
  
        config = { ...config, ...options };
        
        this.attachGlobalListeners();
        
        console.log(`[Seal] Initialized for ${config.appName}. Watching for errors...`);
  
        if (config.rescueEngine) {
          console.log('[Seal] Rescue Engine Enabled. Fetching active patches...');
          this.fetchAndApplyPatches();
        }
      },
  
      /**
       * Attach window level error and unhandled rejection listeners
       */
      attachGlobalListeners: function() {
        // Standard JS Errors
        window.onerror = function(message, source, lineno, colno, error) {
          Seal.reportError({
            type: 'TypeError/Error',
            message: message,
            stack: error ? error.stack : '',
            context: { source, lineno, colno }
          });
          return false; // Let default browser handling proceed
        };
  
        // Promises
        window.addEventListener('unhandledrejection', function(event) {
          Seal.reportError({
            type: 'UnhandledRejection',
            message: event.reason ? event.reason.message || String(event.reason) : 'Unknown Promise Rejection',
            stack: event.reason && event.reason.stack ? event.reason.stack : '',
            context: { type: 'promise' }
          });
        });
      },
  
      /**
       * Send the error payload to the Seal Backend
       */
      reportError: function(errorData) {
        if (!config.apiKey) return;
  
        const payload = {
          app_name: config.appName,
          message: errorData.message,
          stack_trace: errorData.stack || 'No stack trace available',
          level: 'error',
          context: errorData.context
        };
  
        fetch(`${config.apiEndpoint}/ingest`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${config.apiKey}`
          },
          body: JSON.stringify(payload)
        }).catch(err => {
          // Silent catch to prevent infinite error loops
          console.error('[Seal] Failed to report error to backend.');
        });
      },
  
      /**
       * Fetch active patches for this app and execute them in a sandboxed context
       */
      fetchAndApplyPatches: function() {
        // Example implementation for fetching patches generated by the AI
        fetch(`${config.apiEndpoint}/patches?app_name=${encodeURIComponent(config.appName)}`, {
          headers: {
            'Authorization': `Bearer ${config.apiKey}`
          }
        })
        .then(res => res.json())
        .then(data => {
          if (data && data.patches && data.patches.length > 0) {
            data.patches.forEach(patch => {
              try {
                // Warning: Evaluating remote code. 
                // In production, this runs inside a controlled, isolated context.
                const patchFn = new Function(patch.code);
                patchFn();
                console.log(`[Seal] Applied patch ID: ${patch.id}`);
              } catch(e) {
                console.warn(`[Seal] Failed to apply patch ${patch.id}`, e);
              }
            });
          }
        })
        .catch(err => {
          // Silent catch
        });
      }
    };
  
    // Expose to global window object
    window.Seal = Seal;
  
  })(window);
  
